eattitude<-datasets::attitude
head(eattitude,10)
tail(eattitude,10)
summary(eattitude)
summary(eattitude$rating)
summary(eattitude$complaints)
plot(eattitude$rating)
boxplot(eattitude$rating,type='l')
plot(eattitude$complaints,type = 'p')
hist(eattitude)
hist(eattitude$privileges)
sd(eattitude$rating)
skewness(eattitude$advance)
kurtosis(eattitude$raises)
plot(eattitude$complaints,xlab = 'summary of complaints')
