ecars<-Cars_
head(Cars_,10)
tail(Cars_,10)
summary(Cars_)
summary(Cars_$HP)
summary(Cars_$MPG)
summary(Cars_$VOL)
summary(Cars_$SP)
summary(Cars_$WT)
plot(Cars_$HP)
plot(Cars_$MPG)
plot(Cars_$VOL)
plot(Cars_$SP)
plot(Cars_$WT)
barplot(Cars_$HP)
barplot(Cars_$WT)
boxplot(Cars_$HP)
boxplot(Cars_$WT)
plot(Cars_$HP,Cars_$WT,type = 'l')
plot(Cars_$HP,Cars_$MPG,type = 'p')
plot(Cars_$WT,main = 'summary')
plot(Cars_$SP,xlab = 'rise in sp')
hist(Cars_$HP)
hist(Cars_)
var(Cars_$HP)
sd(Cars_$WT)
mean(Cars_$HP)
skewness(Cars_$VOL)
kurtosis(Cars_$WT)
