life<-datasets::LifeCycleSavings
head(life,10)
tail(life,10)
summary(life)
summary(life$pop15)
Summary(life$pop75)
plot(life$sr)
plot(life$pop15)
plot(life$pop75)
plot(life$dpi,type = 'l')
barplot(life$dpi)
barplot(life$ddpi)
boxplot(life$pop75)
boxplot(life$dpi)
hist(life$sr)
hist(life$pop15)
sd(life$pop15)
