ebeaver<-datasets::beaver1
head(ebeaver,10)
tail(ebeaver,10)
summary(ebeaver)
summary(ebeaver$day)
summary(ebeaver$time)
summary(ebeaver$temp)
summary(ebeaver$activ)
plot(ebeaver$day,ebeaver$time)
plot(ebeaver$temp,ebeaver$activ)
barplot(ebeaver$day,type='l')
plot(ebeaver$time,type = 'l')
plot(ebeaver$temp,type = 'p')
boxplot(ebeaver)
skewness(ebeaver$day)
sd(ebeaver$time)
var(ebeaver$activ)
kurtosis(ebeaver$temp)
hist(ebeaver$day)
