ebod<-datasets::BOD
head(ebod,1)
tail(ebod,1)
summary(ebod$Time)
summary(ebod$demand)
plot(ebod$Time,main = 'l')
plot(ebod$demand,type = 'p')
plot(ebod$Time,ebod$demand,type = 'l')
barplot(ebod$Time)
barplot(ebod$demand)
sd(ebod$Time)
sd(ebod$demand)
skewness(ebod$Time)
kurtosis(ebod$demand)
boxplot(ebod$Time,ebod$demand)
skewness(ebod$Time)
