echickwts<-datasets::chickwts
head(echickwts,10)
tail(echickwts,10)
summary(echickwts)
summary(echickwts$weight)
summary(echickwts$feed)
plot(echickwts$weight)
plot(echickwts$weight,type = 'l')
plot(echickwts$feed)
boxplot(echickwts$weight)
boxplot(echickwts$feed)
barplot(echickwts$weight)
barplot(echickwts$feed)
plot(echickwts$weight,xlab = 'summary')
plot(echickwts$feed,main='summary')
skewness(echickwts$weight)
kurtosis(echickwts$weight
sd(echickwts$weight)         
sd(echickwts$feed)
var(echickwts$weight)
mean(echickwts$weight)
