inf<-datasets::infert
head(inf,10)
tail(inf,10)
summary(inf)
summary(inf$education)
summary(inf$age)
summary(inf$pooled.stratum)
summary(inf$induced)
plot(inf$age)
plot(inf$age,type = 'l')
plot(inf$case)
plot(inf$pooled.stratum)
plot(inf$pooled.stratum,type = 'l')
barplot(inf$education)
barplot(inf$pooled.stratum)
boxplot(inf$stratum)
hist(inf$parity)
