eanscombe<-datasets::anscombe
head(eanscombe,10)
tail(eanscombe,10)
summary(eanscombe)
summary(eanscombe$x1)
summary(eanscombe$x4)
summary(eanscombe$x4)
plot(eanscombe$x1)
plot(eanscombe$x3)
plot(eanscombe$y4,type = 'l')
barplot(eanscombe$x3)
boxplot(eanscombe$y3)
hist(eanscombe$x1)
hist(eanscombe$x4)
skewness(eanscombe$x1)
kurtosis(eanscombe$x3)
sd(eanscombe$x2)
