echick<-datasets::chickwts
head(echick,10)
tail(echick,10)
summary(echick$weight)
summary(echick$feed)
plot(echick$weight)
plot(echick$feed)
barplot(echick$weight)
barplot(echick$feed)
boxplot(echick$weight)
boxplot(echick$feed)
plot(echick$weight,type = 'l')
hist(echick$weight)
hist(echick$feed)
plot(echick$weight,xlab = 'd')
var(echick$weight)
var(echick$feed)
sd(echick$weight)
skewness(echick$weight)
kurtosis(echick$weight)
