formal<-datasets::Formaldehyde
head(formal,10)
tail(formal,6)
summary(formal)
summary(formal$carb)
summary(formal$optden)
plot(formal$carb)
plot(formal$optden)
plot(formal$carb,type = 'l')
plot(formal$optden,type = 'l')
boxplot(formal$carb)
boxplot(formal$optden)
barplot(formal$carb)
barplot(formal$optden)
hist(formal$carb)
hist(formal$optden)
sd(formal$carb)
skewness(formal$optden)
kurtosis(formal$optden)
mean(formal$carb)
