i<-datasets::iris
head(i,10)
tail(i,10)
summary(i)
summary(i$Sepal.Length)
summary(i$Sepal.Width)
plot(i$Sepal.Length)
plot(i$Sepal.Width)
plot(i$Petal.Length)
plot(i$Petal.Width)
plot(i$Sepal.Length,type = 'l')
plot(i$Sepal.Length,xlab = 'index',col='red',horiz=TRUE)
barplot(i$Sepal.Length)
barplot(i$Petal.Length)
boxplot(i$Petal.Length)
boxplot(i$Species)
hist(i$Sepal.Length)
plot(i$Sepal.Length)
sd(i$Sepal.Length)
skewness(i$Petal.Width)
kurtosis(i$Species)
