esoph<-datasets::esoph
head(esoph,10)
tail(esoph,10)
summary(esoph)
summary(esoph$agegp)
summary(esoph$alcgp)
summary(esoph$tobgp)
plot(esoph$tobgp)
plot(esoph$ncases)
plot(esoph$ncontrols)
plot(esoph$ncases,type = 'l')
barplot(esoph$ncontrols)
barplot(esoph$ncases)
boxplot(esoph$agegp)
boxplot(esoph$alcgp)
plot(esoph$ncases,main = 'summary')
hist(esoph$agegp)
hist(esoph$ncontrols)
skewness(esoph$agegp)
skewness(esoph$ncases)
kurtosis(esoph$ncontrols)
sd(esoph$ncontrols)
mean(esoph$ncases)
