efaithful<-datasets::faithful
head(efaithful$eruptions)
head(efaithful,10)
tail(efaithful,10)
summary(efaithful$eruptions)
summary(efaithful$waiting)
plot(efaithful$eruptions
plot(efaithful$waiting)     
plot(faithful$eruptions)
plot(efaithful$waiting)
plot(efaithful$eruptions,efaithful$waiting)
plot(efaithful$eruptions,type = 'l')
plot(efaithful$waiting,xlab = 'summary')
barplot(efaithful$eruptions)
barplot(efaithful$waiting)
boxplot(efaithful$eruptions)
boxplot(efaithful$waiting)
skewness(efaithful$eruptions)
skewness(efaithful$waiting)
sd(efaithful$eruptions)
kurtosis(efaithful$waiting)
